### ISSUE TITLE
eslint config and lint tests for workflows

### ISSUE THREAD

**Issue by probablyArth** [sanny-io/react-appwrite#16] opened 2023-03-30 09:57 UTC
To ensure strict rules and prevent unnecessary file changes in future, it could be a great addition.

And we can use eslint to enforce linting tests for CI/CD as well.

**Comment by sanny-io** [comment] 2023-03-31 07:21
This is a duplicate of #14 

I am going to start on that this weekend, among other changes. eslint looks pretty cool. Will probably end up using that if there are no objections 🙂

**Closed by sanny-io** 2023-03-31 07:21 UTC
